### ISSUE TITLE
pperf errors on adapter

### ISSUE THREAD

**Issue by nicolas-martin** [stgnet/phtest#2]
Works fine on linux and mac, however when running on the adapter pperf fails with `received wrong data crc`

```
GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -v -ldflags="-s -w" -o pperf.mipsle ./cmd/pperf/ && scp -i ~/.ssh/ph -o StrictHostKeyChecking=no ./pperf.mipsle root@192.168.177.1:/tmp/
```

then running 

```
root@OpenWrt:~# /tmp/pperf.mipsle -target 66.165.239.42
Remote error: received wrong data crc
```

**Comment by stgnet** [comment]
Interesting.  I would strongly suspect that the binary conversion
(big-little endian) is failing to correct for the mips architecture.  There
could be some other cause as well.  I can add an endian detection into the
protocol to detect that failure.  Go ahead and file a
privacy-hero/issue/issue for this and assign it to me.

------------------------------
     Scott Griepentrog   +1-256-580-6090 http://theB.life
